const Koa = require('koa')
const bodyParser = require('koa-bodyparser')

const controller = require('./controller')
const template = require('./template/nunjuckstpl.js')

const app = new Koa()

app.use(async (ctx, next) => {
    console.log('------')
    console.log(`Process ${ctx.request.method} ${ctx.request.url} ...`)
    await next()
})

app.use(async (ctx, next) => {
    const start = Date.now()
    await next()
    const end = Date.now() - start
    console.log(`time cost: ${end}ms`)
})

app.use(async (ctx, next) => { //generated by nunjucks 
    await next()
    ctx.response.body += template
})

app.use(bodyParser())

app.use(controller())

app.listen(3000)
console.log('koa2 listening on port 3000')